use crate::tokens::{Token, LexicalError};
use crate::ast;

grammar;

extern {
  type Location = usize;
  type Error = lexer::LexicalError;

  enum Token {
    "program" => Token::KeywordProgram,
    "main" => Token::KeywordMain,
    "print" => Token::KeywordPrint,
    "if" => Token::KeywordIf,
    "else" => Token::KeywordElse,
    "while" => Token::KeywordWhile,
    "do" => Token::KeywordDo,
    "end" => Token::KeywordEnd,
    "int" => Token::KeywordInt,
    "cte_int" => Token::CteInt,
    "float" => Token::KeywordFloat,
    "cte_float" => Token::CteFloat,
    "cte.string" => Token::CteString,
    "var" => Token::KeywordVar,
    "void" => Token::KeywordVoid,
    "id" => Token::Identifier(<String>),
    "integer" => Token::Integer(<i64>),
    "float" => Token::Float(<f64>),
    "(" => Token::LParen,
    ")" => Token::RParen,
    "[" => Token::LBraket,
    "]" => Token::RBraket,
    "{" => Token::LBrace,
    "}" => Token::RBrace,
    "=" => Token::AssignSimbol,
    ":" => Token::TwoPoints,
    "!=" => Token::NotEqual,
    ">" => Token::BigerThan,
    "<" => Token::SmallerThan,
    ";" => Token::Semicolon,
    "," => Token::Comma,
    "+" => Token::OperatorAdd,
    "-" => Token::OperatorSub,
    "*" => Token::OperatorMul,
    "/" => Token::OperatorDiv,
  }
}

#[inline]
Id: String = {
    <s:"id"> => s
};

#[inline]
Integer: i64 = {
    <n:"integer"> => n
};

#[inline]
Float: f64 = {
    <n:"float"> => n
};

#[inline]
Type: String = {
    "int" => "int".to_string(),
    "float" => "float".to_string(),
};

#[inline]
Cte: Expression = {
    <n:"integer"> => Expression::Integer(n)
};

#[inline]
CteFloat: Expression = {
    <n:"float"> => Expression::Float(n)
};


#[inline]
CompOp: BinaryOperator = {
    ">" => BinaryOperator::GreaterThan,
    "<" => BinaryOperator::LessThan,
    "!=" => BinaryOperator::NotEqual,
};
// ---------------------------------------------------- Program -------------------------------------------------------

pub Program: Program = {
    "program" <fid:Id> ";" <decls:Declaration*> "main" <mainb:Body> "end" => Program {
        id: fid,
        declarations: decls,
        body: mainb,
    }
};

Declaration: Declaration = {
    <var:VarDecl> => Declaration::Var(var),
    <func:Function> => Declaration::Func(func),
};

// ---------------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------- Vars -------------------------------------------------------

// Vars: Vec<VarDecl> = {
//     <decls:VarDecl*> => decls,
// };

VarDecl: VarDecl = {
    "var" <first:Id> <rest:("," <Id>)*> ":" <ty:Type> ";" => {
        let mut names = vec![first];
        names.extend(rest.into_iter().map(|(_, id)| id));
        VarDecl { names, var_type: ty }
    }
};
// ----------------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------- Functions -------------------------------------------------------
// Function: Func = {
//     "void" <id:Id> "(" <params:ParamList> ")" "[" <vars:VarDecl?> <body:Body> "]" ";" => Func {
//         name: id,
//         params,
//         vars: vars.unwrap_or(vec![]),
//         body,
//     }
// };

Function: Func = {
    "void" <id:Id> "(" <params:ParamList> ")" "[" <body:Body> "]" ";" => Func {
        name: id,
        params,
        vars: vec![],
        body,
    },
    "void" <id:Id> "(" <params:ParamList> ")" "[" <vars:VarDecl> <body:Body> "]" ";" => Func {
        name: id,
        params,
        vars: vec![vars],
        body,
    }
};

// ParamList: Vec<Param> = {
//     <p:Param> <rest:("," <Param>)*> => {
//         let mut list = vec![p];
//         list.extend(rest.into_iter().map(|(_, p)| p));
//         list
//     },
//     => vec![],
// };


ParamList: Vec<Param> = {
    <params:ParamListNonEmpty?> => params.unwrap_or(vec![]),
};

ParamListNonEmpty: Vec<Param> = {
    <p:Param> => vec![p],
    <p:Param> "," <rest:ParamListNonEmpty> => {
        let mut list = vec![p];
        list.extend(rest);
        list
    },
};

// ParamList: Vec<Param> = {
//     => vec![], // Lista vacía
//     <first:Param> <rest:("," <Param>)*> => {
//         let mut params = vec![first];
//         params.extend(rest.into_iter().map(|(_, p)| p));
//         params
//     }
// };

Param: Param = {
    <name:Id> ":" <ty:Type> => Param {
        name,
        param_type: ty,
    }
};


//------------------------------------------------------------------------------------------------------------------------------------

//---------------------------------------------- Body -----------------------------------------------

// Cuerpo ficticio (puedes hacer algo más complejo)
pub Body: Vec<Statement> = {
    "{" <stmts:Statement*> "}" => stmts
};
//-------------------------------------------------------------------------------------------------------------------------------


// ----------------------------------------------------- Statement ------------------------------------------------------
// ----------------------------------------------------- |_ Assign ------------------------------------------------------
// ----------------------------------------------------- |_ Condition ---------------------------------------------------
// ----------------------------------------------------- |_ Cycle -------------------------------------------------------
// ----------------------------------------------------- |_ F_Call ------------------------------------------------------
// ----------------------------------------------------- |_ Print -------------------------------------------------------

pub Statement: Statement = {
    <s:Assign> => s,
    <s:Condition> => s,
    <s:Cycle> => s,
    <s:F_Call> => s,
    <s:Print> => s
};

// ---------------------------- Assign
pub Assign: Statement = {
    <id:Id> "=" <e:Expression> ";" => Statement::Variable {
      id: id,
      value: Box::new(e),
    }
};

// ---------------------------- Condition

pub Condition: Statement = {
    "if" "(" <e:Expression> ")" <then_body:Body> "else" <else_body:Body> ";" => Statement::Condition {
        condition: Box::new(e),
        then_branch: then_body,
        else_branch: else_body,
    },
    "if" "(" <e:Expression> ")" <then_body:Body> ";" => Statement::Condition {
        condition: Box::new(e),
        then_branch: then_body,
        else_branch: vec![],
    }
};

// ---------------------------- Cycle
pub Cycle: Statement = {
  "while" "(" <e:Expression> ")" "do" <b:Body> ";" => Statement::Cycle {
      condition: Box::new(e),
      body: b,
  }
};

// ---------------------------- F_Call
// pub F_Call: Statement = {
//     <id:Id> "(" <firstarg:Expression> <rest:("," <Expression>)*> ")" ";" => {
//         let mut args = vec![firstarg];
//         args.extend(rest.into_iter().map(|(_, expr)| expr));
//         Statement::FCall { id, args }
//     },
//     <id:Id> "(" ")" ";" => Statement::FCall { id, args: vec![] }
// };
pub F_Call: Statement = {
    //No argumentos
    <id:Id> "(" ")" ";" => Statement::FCall { id, args: vec![] },
    //uno o mas argumentos
    <id:Id> "(" <first:Expression> <rest:("," <Expression>)*> ")" ";" => {
        let mut args = vec![first];
        args.extend(rest.into_iter().map(|(_, e)| e));
        Statement::FCall { id, args }
    }
};

// ---------------------------- Print
Print: Statement = {
    "print" <val:Expression> ";" => Statement::Print {
        value: Box::new(val),
    },
};

// -------------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------- Expression ---------------------------------------------------
//Expression para operadores de comparacion

pub Expression: Expression = {
    //nivel 0 elementos basicos, mayor precedencia sin asociatividad
    #[precedence(level="0")]
    "(" <e:Expression> ")" => e,
    #[precedence(level="0")]
    "-" <e:Cte> => Expression::Binary {
        left: Box::new(Expression::Integer(0)),
        operator: BinaryOperator::Sub,
        right: Box::new(e),
    },
    #[precedence(level="0")]
    "+" <e:Cte> => Expression::Binary {
        left: Box::new(Expression::Integer(0)),
        operator: BinaryOperator::Add,
        right: Box::new(e),
    },
    #[precedence(level="0")]
    "-" <e:CteFloat> => Expression::Binary {
        left: Box::new(Expression::Float(0.0)),
        operator: BinaryOperator::Sub,
        right: Box::new(e),
    },
    #[precedence(level="0")]
    "+" <e:CteFloat> => Expression::Binary {
        left: Box::new(Expression::Float(0.0)),
        operator: BinaryOperator::Add,
        right: Box::new(e),
    },
    #[precedence(level="0")]
    <e:Id> => Expression::Variable(e),
    #[precedence(level="0")]
    <e:Cte> => e,
    #[precedence(level="0")]
    <e:CteFloat> => e,

    //nivel 1 multiplicacion y division, alta precedencia
    #[precedence(level="1")] #[assoc(side="left")]
    <left:Expression> "*" <right:Expression> => Expression::Binary {
        left: Box::new(left),
        operator: BinaryOperator::Mul,
        right: Box::new(right),
    },
    #[precedence(level="1")] #[assoc(side="left")]
    <left:Expression> "/" <right:Expression> => Expression::Binary {
        left: Box::new(left),
        operator: BinaryOperator::Div,
        right: Box::new(right),
    },

    //nivel 2 suma y resta precedencia media
    #[precedence(level="2")] #[assoc(side="left")]
    <left:Expression> "+" <right:Expression> => Expression::Binary {
        left: Box::new(left),
        operator: BinaryOperator::Add,
        right: Box::new(right),
    },
    #[precedence(level="2")] #[assoc(side="left")]
    <left:Expression> "-" <right:Expression> => Expression::Binary {
        left: Box::new(left),
        operator: BinaryOperator::Sub,
        right: Box::new(right),
    },

    //nivel 3 comparaciones menor precedencia
    #[precedence(level="3")] #[assoc(side="left")]
    <left:Expression> ">" <right:Expression> => Expression::Binary {
        left: Box::new(left),
        operator: BinaryOperator::GreaterThan,
        right: Box::new(right),
    },
    #[precedence(level="3")] #[assoc(side="left")]
    <left:Expression> "<" <right:Expression> => Expression::Binary {
        left: Box::new(left),
        operator: BinaryOperator::LessThan,
        right: Box::new(right),
    },
    #[precedence(level="3")] #[assoc(side="left")]
    <left:Expression> "!=" <right:Expression> => Expression::Binary {
        left: Box::new(left),
        operator: BinaryOperator::NotEqual,
        right: Box::new(right),
    },
};